server {
  listen 80;
  server_name _;
  location / {
    root /usr/share/nginx/html;
    autoindex off;
    add_header Cache-Control "no-store";
  }
  location /health {
    return 200 '{"ok":true}';
    add_header Content-Type application/json;
  }
}
